POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "zzezeaezaer",
    "email": "qzcaa@html.fr",
    "password": "kek1234"
}

###
GET http://localhost:8080/users/1

###

POST http://localhost:8080/projects
Content-Type: application/json

{
  "name": "Test ProjezczzteE",
  "user": {
    "id": 1
  }
}

###
GET http://localhost:8080/users/1/projects


###

GET http://localhost:8080/projects/1
