POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "zzezeaeeeeerrezezer",
    "email": "qzcaaaa@ae.fe",
    "password": "kek1234"
}

###
GET http://localhost:8080/users/1

###

POST http://localhost:8080/projects
Content-Type: application/json

{
  "name": "Test ProjezczzteE",
  "user": {
    "id": 1
  }
}

###
GET http://localhost:8080/users/1/projects


###

GET http://localhost:8080/projects/1

###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Test TaskzzzzzzZzzzeze",
  "status": "TODO",
  "project": {
    "id": 1
  },
  "user": {
    "id": 1
  }
}

###
GET http://localhost:8080/users/1/tasks


### 
GET http://localhost:8080/projects/1/tasks


###
PATCH http://localhost:8080/tasks/1
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "zzezeaeeeeerrezezer",
  "password": "kek1234"
}
